### ISSUE TITLE
Cannot call TraceEventViewer

### ISSUE THREAD

**Issue by adiprerepa** [perfmark/perfmark#31]
I am trying to implement PerfMark in netflix/zuul, in one of the examples. I added the dependency to the `zuul-sample` level `build.gradle`, but for some reason, I cannot call `TraceEventViewer.writeTraceHtml();`. Is there a reason for this? I'm kind of a newbie at PerfMark, and want to learn more about it.

**Comment by adiprerepa** [comment]
I was also wondering if there was a "help needed" section or something where people could work on tickets for PerfMark?

**Comment by ejona86** [comment]
Which dependency did you add and what error do you get?

**Comment by adiprerepa** [comment]
The error I get is :
```
error: cannot find symbol
            TraceEventViewer.writeHtml();
            ^
  symbol:   variable TraceEventViewer
  location: class Bootstrap
```
I am using `compile "io.perfmark:perfmark-api:0.20.1"`

**Comment by ejona86** [comment]
TraceEventViewer is part of `io.perfmark:perfmark-traceviewer`

**Comment by adiprerepa** [comment]
ah thank you.
