### ISSUE TITLE
Caused by: java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by Licarey** [perfmark/perfmark#34]
this  is runtimeException :

     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: [Ljava/nio/file/attribute/FileAttribute;
        at io.perfmark.traceviewer.TraceEventViewer.writeTraceHtml(TraceEventViewer.java:90)

**Comment by creamsoup** [comment]
this must be on android. 
afaik, Perfmark doesn't support android. @carl-mastrangelo can you confirm this?

Android api 26 added the missing class, you maybe can use it if you are using android api 26+.

**Comment by carl-mastrangelo** [comment]
@Licarey This is likely because trace writer depends on Java 1.7.   Android added support for it in API level 26:

https://developer.android.com/reference/java/nio/file/attribute/FileAttribute
