### ISSUE TITLE
Consider making PerfMark accept `Object` for tags 

### ISSUE THREAD

**Issue by carl-mastrangelo** [perfmark/perfmark#4]
Changing `PerfMark.createTag(Object name)` instead of `PerfMark.createTag(String name)` would allowing the implementation to call toString() late in case PerfMark is disabled.  Calling toString() is also kind of verbose, when it's trivial for PerfMark to call `String.valueOf()`.

**Comment by dapengzhang0** [comment]
Also `PerfMark.createTag(String nameTemplate, Object ... nameArgs)` in the same pattern as https://static.javadoc.io/com.google.guava/guava/28.0-jre/com/google/common/base/Preconditions.html#checkArgument-boolean-java.lang.String-java.lang.Object...-

**Comment by adiprerepa** [comment]
Not sure if this is still a priority. Where is `Impl.java` in `/api` being implemented?

**Comment by carl-mastrangelo** [comment]
@adiprerepa It's implemented here: https://github.com/perfmark/perfmark/blob/master/impl/src/main/java/io/perfmark/impl/SecretPerfMarkImpl.java

The issue here is `Object` is a kind of surprising API

**Comment by carl-mastrangelo** [comment]
After toying with the lambda string function in master, I think passing object here is a mistake.  Passing in a strongly typed value value and stringer I think is a better long term API, because Object is too easy to misuse (despite it being correct).
