### ISSUE TITLE
Do not use version ranges?

### ISSUE THREAD

**Issue by dapengzhang0** [perfmark/perfmark#6]
[JLBP](https://jlbp.dev/) suggests [Do not use version ranges](https://jlbp.dev/JLBP-14.html)

The issue https://github.com/grpc/grpc-java/issues/6217 may be related.

**Comment by ejona86** [comment]
Although, this usage is similar to "Single-element version ranges". I guess the bigger question is why does it need to be pinned.

**Comment by dapengzhang0** [comment]
@ejona86 What is "Single-element version ranges"? Correct me if I'm wrong, my understanding of "Single-element version ranges" (“hard requirements”) is like [2.3.2, 2.3.2] where the upper bound is exactly equal to the lower bound, which is not the case in perfmark.

**Comment by ejona86** [comment]
Yes (although it would be written as `[2.3.2]`), but the main alternative it was considering was more open ranges, where new versions could be released later. In this case there are just two versions that match and the maximum possible release has already been released.

That said, it does seem like a bad thing to pin here if we are able to avoid it. It shouldn't be allowed to continue and fester.

**Comment by dapengzhang0** [comment]
This is blocking adding Android projects to Firebase. I hope this issue can be resolved in the next release.

**Comment by carl-mastrangelo** [comment]
I accidentally unsubscribed from this repo.  The version range was used originally to deal with gRPC being stuck on 2.3.2, but I guess thats fixed now.
