### ISSUE TITLE
does it support java8 in maven project?

### ISSUE THREAD

**Issue by LucasDove** [perfmark/perfmark#61]
I am using java1.8 and maven for project managing. But I cannot download the jar file even if I explicitly declare perfmark-tracewriter in the pom.xml

**Comment by ejona86** [comment]
What error do you get? Perfmark supports as far back as Java 6. The Java version shouldn't impact packaging at all.

**Comment by LucasDove** [comment]
thanks for replying. it turns out to be network problems or something else and it's all good now.
gonna close this one
